import { execa } from 'execa';
import { Scanner, ScanResult } from './base.scanner';
import { Finding, Severity, ScanConfig } from '@openvscan/types';
import * as fs from 'fs/promises';
import * as path from 'path';
import * as os from 'os';

export class TrivyScanner implements Scanner {
  name = 'Trivy';

  async isAvailable(): Promise<boolean> {
    try {
      await execa('trivy', ['--version']);
      return true;
    } catch {
      return false;
    }
  }

  async scan(target: string, config?: ScanConfig): Promise<ScanResult> {
    const isAvailable = await this.isAvailable();
    if (!isAvailable) {
      throw new Error('Trivy is not installed or available in PATH');
    }

    // Determine scan type based on target (image vs fs)
    // Simple heuristic: if it looks like a URL/repo, clone it first?
    // For now, assume target is a path or image name.
    // If we want to scan a repo, we might need a separate 'Clone' step in the worker pipeline.

    // For this implementation, we'll assume 'fs' scan on a path or 'image' scan
    const scanType = target.includes('/') && !target.startsWith('/') ? 'image' : 'fs';

    // Create temp file for JSON output
    const tempDir = os.tmpdir();
    const outputPath = path.join(tempDir, `trivy-result-${Date.now()}.json`);

    try {
      const args = [
        scanType,
        '--format', 'json',
        '--output', outputPath,
        '--no-progress',
        target
      ];

      console.log(`[Trivy] Running command: trivy ${args.join(' ')}`);
      await execa('trivy', args);

      const rawOutput = await fs.readFile(outputPath, 'utf-8');
      const findings = this.parseFindings(rawOutput);

      return {
        findings,
        rawOutput
      };
    } finally {
      // Cleanup
      try {
        await fs.unlink(outputPath);
      } catch {}
    }
  }

  private parseFindings(jsonOutput: string): Finding[] {
    try {
      const data = JSON.parse(jsonOutput);
      const findings: Finding[] = [];

      if (!data.Results) return [];

      for (const result of data.Results) {
        if (!result.Vulnerabilities) continue;

        for (const vuln of result.Vulnerabilities) {
          findings.push({
            id: vuln.VulnerabilityID, // This will be replaced/generated by DB usually, but using CVE ID as ref for now
            scanId: '', // To be filled by processor
            title: vuln.Title || vuln.VulnerabilityID,
            description: vuln.Description,
            severity: this.mapSeverity(vuln.Severity),
            location: result.Target,
            remediation: `Upgrade to ${vuln.FixedVersion || 'latest version'}`,
            tool: 'trivy',
            createdAt: new Date()
          });
        }
      }

      return findings;
    } catch (error) {
      console.error('Failed to parse Trivy output', error);
      return [];
    }
  }

  private mapSeverity(severity: string): Severity {
    switch (severity.toUpperCase()) {
      case 'CRITICAL': return Severity.CRITICAL;
      case 'HIGH': return Severity.HIGH;
      case 'MEDIUM': return Severity.MEDIUM;
      case 'LOW': return Severity.LOW;
      default: return Severity.INFO;
    }
  }
}
